<a href="https://colab.research.google.com/github/Israwss/Datos-Masivos-II/blob/main/DMII_U1_1_eigenvalues.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Datos Masivos II

## Ciencia de datos - IIMAS


### Unidad 1. Reducción de dimensionalidad

#### 1.1. Calculo de vectores y valores propios

Una matriz $A$ de tamaño $nxn$ se puede descomponer en un conjunto de vectores propios (eigenvectores) ($x$) y valores propios (eigenvalores) ($\lambda$)

de manera que:

Los valores $\lambda$ que satisfacen la relación:
  
$(A-\lambda I)=0$

se llaman **eigenvalores o valores propios**.

La solución $x$ que satisface:

$(A-\lambda I)x=0$

se llama **eigenvectores o vectores propios**.

Para calcular la descomposición de una matriz A, emplearemos la función de Numpy llamada eig().


 Fuente: https://github.com/blancavazquez/CursoDatosMasivosII



La libreria SciPy también contiene un submódulo linalg y existe una superposición en la funcionalidad proporcionada por SciPy y Numpy. En Scipy se tiene algunas funciones adicionales como la descomposición LU y Schur.
Sin embargo, la función de Numpy pueden ser más flexibles.

In [ ]:
import numpy as np
from numpy import array
from numpy.linalg import eig


In [ ]:
#Define una matriz A
A=array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
print(A)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [ ]:
#Calcula los valores y vectores propios
eigenvalues, eigenvectors=eig(A)
print("Eigenvalores: \n", eigenvalues)
print("Eigenvectores: \n", eigenvectors)

Eigenvalores: 
 [ 1.61168440e+01 -1.11684397e+00 -5.03850873e-16]
Eigenvectores: 
 [[-0.8186735  -0.61232756  0.40824829]
 [-0.52532209  0.08675134 -0.81649658]
 [-0.23197069  0.78583024  0.40824829]]


# Reconstrucción de la matriz original

Es posible reconstruir la matriz original a partir de los vectores propios y valores propios.

Vamos a utilizar la siguiente ecuación:

$A=UDU^{-1}$

Donde:

$A$ es una matriz original que se desea reconstruir

$U$ es una matriz que contiene los vectores propios de $A$

$D$ es una matriz diagonal que contiene los valores propios de $A$

$U^{-1}$ Es la matriz inversa de $U$

In [ ]:
from numpy import diag
from numpy import dot
from numpy.linalg import inv
from numpy import array
from numpy.linalg import eig

In [ ]:
#Se define la matriz
A = array([[1,2,3],[4,5,6],[7,8,9]])
print("Matriz \n", A)
#Calcular los valores y vectores propios
valores, vectores = eig(A)
print("Eigenvalores: \n", valores)
print("Eigenvalores: \n", vectores)

Matriz 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Eigenvalores: 
 [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
Eigenvalores: 
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [ ]:
#Crear una matriz a partir de los vectores propios
m_vectores_propios = vectores
print(m_vectores_propios)

[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [ ]:
#Crear una matriz inversa de los vectores propios
m_inversa = inv(m_vectores_propios)
print(m_inversa)

[[-0.48295226 -0.59340999 -0.70386772]
 [-0.91788599 -0.24901003  0.41986593]
 [ 0.40824829 -0.81649658  0.40824829]]


In [ ]:
#Crear una matriz diagonal para los valores propios
m_diagonal = diag(valores)
print(m_diagonal)

[[ 1.61168440e+01  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.11684397e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.30367773e-15]]


In [ ]:
#Reconstruir la matriz original, usando la función producto punto .dot() de numpy
m_original = m_vectores_propios.dot(m_diagonal).dot(m_inversa)
print(m_original)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# **Método de potencias**


El método de potencias es un algoritmo iterativo utilizado para calcular el valor propio dominante (el valor propio de mayor magnitud) y su correspondiente vector propio de una matriz cuadrada $A$. Este método es especialmente útil cuando solo se necesita el mayor valor propio y su vector asociado, en lugar de todos los valores y vectores propios de la matriz.

El primer código está basado de [Power iteration](http://mlwiki.org/index.php/Power_Iteration) y el segundo de [UCG](https://www.ucg.ac.me/skladiste/blog_10701/objava_23569/fajlovi/power.pdf)

In [ ]:
def eigenvalue(A, v):
    # Esta función calcula el valor propio asociado al vector propio v.
    # Multiplica la matriz A por el vector v
    Av = A.dot(v)
    # Calcula el producto escalar entre v y Av, que aproxima el valor propio
    return v.dot(Av)

def power_iteration(A):
    # Obtiene el tamaño de la matriz (número de filas o columnas, asumiendo que es cuadrada)
    n = A.shape[0]

    # Inicializa el vector v con valores iguales y normalizados (norma L2)
    v = np.ones(n) / np.sqrt(n)
    print("v:", v)

    # Calcula el valor propio inicial utilizando el vector inicial v
    ev = eigenvalue(A, v)

    while True:
        # Multiplica la matriz A por el vector v
        Av = A.dot(v)

        # Normaliza el vector resultante Av para obtener un nuevo vector v_new
        v_new = Av / np.linalg.norm(Av)

        # Calcula el nuevo valor propio asociado a v_new
        ev_new = eigenvalue(A, v_new)

        # Verifica la convergencia: si la diferencia entre el valor propio anterior y el nuevo
        # es menor a un umbral (0.01 en este caso), se detiene la iteración
        if np.abs(ev - ev_new) < 0.01:  # np.abs() calcula el valor absoluto
            print("Umbral:", np.abs(ev - ev_new))
            break

        # Actualiza el vector v y el valor propio ev para la próxima iteración
        v = v_new
        ev = ev_new

    # Retorna el valor propio final calculado y el vector propio asociado
    return ev_new, v_new

In [ ]:
#Se define la matriz
A = np.array([[3,2],[2,6]])
power_iteration(A)

v: [0.70710678 0.70710678]
Umbral: 0.0033972229956287237


(np.float64(6.99969780103031), array([0.45415363, 0.89092339]))

In [ ]:
import numpy as np

def power_iteration(A, num_simulations):
    # Inicializa el vector v con valores iguales y normalizados (norma L2)
    v = np.ones(A.shape[0]) / np.sqrt(A.shape[0])

    # Realiza num_simulations iteraciones del método de potencias
    for _ in range(num_simulations):
        # Calcula el producto matriz-vector A * v
        v_new = np.dot(A, v)

        # Normaliza el vector resultante v_new para obtener un nuevo vector v
        v = v_new / np.linalg.norm(v_new)

    # Retorna el vector v tras el número de iteraciones especificado
    return v

# Ejecuta el método de potencias con una matriz 2x2 y 5 iteraciones
power_iteration(np.array([[3, 2], [2, 6]]), 5)

array([0.44778116, 0.89414318])